### ISSUE TITLE
No option for one time Donation?

### ISSUE THREAD

**Issue by ChaituVR** [freeCodeCamp/donate#7]
It says `Help us pay for servers and other costs. Set up a monthly donation you can afford:` 

there is no option for people to donate one time? 

I really like [Khanacademy's Donation page](https://www.khanacademy.org/donate)  

which allows users to donate using Credit Card via Stripe and provides an option for one time Donation, It would be a good option for people who wanted to donate one time, not really necessary though.

**Comment by nsuchy** [comment]
You are able to set up the recurring donation and cancel after it charges you. However I personally would like to see a custom one time donation option. I am not sure how much work on freeCodeCamp's core team with access to the PayPal account it would take to implement this.
